name: Sort TV Channels

on:
  schedule:
    - cron: "0 8 * * *"  # 每天早上8点执行
  workflow_dispatch:  # 也可以手动触发

jobs:
  sort_channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r ./TV/requirements.txt

      - name: Run Python script
        run: |
          python ./TV/sort_channels.py

      - name: Commit and push sorted file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add TV/live.txt
          git commit -m "Update sorted channels" || echo "No changes to commit"
          git push

  clean:
    needs: sort_channels
    runs-on: ubuntu-latest
    steps:
      - name: Delete older workflow runs and artifacts
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1